apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: package1.tanzu.vmware.com.0.0.1
spec:
  refName: package1.tanzu.vmware.com
  releasedAt: "2023-06-08T19:21:04Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.1

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: package1.tanzu.vmware.com
spec:
  displayName: package1
  longDescription: package1.tanzu.vmware.com
  shortDescription: package1.tanzu.vmware.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: package1
spec:
  packageRef:
    refName: package1.tanzu.vmware.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: package1-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
